title: Eba15 stats rstudio
description: Cours “Introduction à UNIX - Jour 1 - l'Ecole de Bioinformatique Aviesan - novembre 2017
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
