title: Eba15 stats rstudio
description: Cours “Statistiques avec R" pour l'Ecole de Bioinformatique Aviesan - septembre 2015
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
